# Generated by Django 4.0.6 on 2022-07-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_owner_alter_building_table_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('apartment_number', models.CharField(max_length=30)),
                ('rent', models.IntegerField(default=0, null=True)),
                ('service_charge_due_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.building')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.owner')),
            ],
            options={
                'db_table': 'apartment',
            },
        ),
    ]
