# Generated by Django 4.0.6 on 2022-08-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_apartmentimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartmentImages',
            new_name='ApartmentImage',
        ),
    ]
