# Generated by Django 4.0.6 on 2022-08-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_rename_apartmentimages_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='paid_service_this_month',
            field=models.BooleanField(default=False),
        ),
    ]
