# Generated by Django 4.0.6 on 2022-08-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_remove_tenant_apartment_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('nomination_start_time', models.DateTimeField(null=True)),
                ('nomination_end_time', models.DateTimeField(null=True)),
                ('voting_start_time', models.DateTimeField(null=True)),
                ('voting_end_time', models.DateTimeField(null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.building')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.owner')),
            ],
            options={
                'db_table': 'committee_election',
            },
        ),
    ]
