# Generated by Django 4.0.6 on 2022-08-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_tenant_apartment_owner'),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeeelection',
            name='owner',
        ),
        migrations.AddField(
            model_name='committeeelection',
            name='elected_committee_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.owner'),
        ),
        migrations.AddField(
            model_name='committeeelection',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(max_length=30)),
                ('committee_election_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.committeeelection')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.owner')),
            ],
            options={
                'db_table': 'nominee',
            },
        ),
        migrations.CreateModel(
            name='CommitteeElectionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_election_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.committeeelection')),
                ('nominee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.nominee')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.owner')),
            ],
            options={
                'db_table': 'election_vote',
            },
        ),
    ]
