# Generated by Django 4.0.6 on 2022-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_remove_committeeelection_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeeelection',
            old_name='elected_committee_member',
            new_name='owner',
        ),
    ]
