# Generated by Django 4.0.6 on 2022-08-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_rename_owner_committeeelection_elected_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeelection',
            name='phase',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
