# Generated by Django 4.0.6 on 2022-08-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_committeeelection_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeelection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
