# Generated by Django 4.0.6 on 2022-08-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_committeeelection_election_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeeelection',
            name='election_no',
        ),
        migrations.AlterField(
            model_name='committeeelection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
