# Generated by Django 4.0.6 on 2022-08-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_tenant_apartment_owner'),
        ('election', '0008_remove_committeeelection_election_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeelectionvote',
            name='nominee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.nominee'),
        ),
        migrations.AlterField(
            model_name='committeeelectionvote',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.owner'),
        ),
        migrations.AlterField(
            model_name='nominee',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.owner'),
        ),
    ]
