# Generated by Django 4.0.6 on 2022-08-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_alter_committeeelectionvote_nominee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeeelectionvote',
            old_name='committee_election_ID',
            new_name='committee_election',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='committee_election_ID',
            new_name='committee_election',
        ),
    ]
