# Generated by Django 4.0.6 on 2022-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_rename_committee_election_id_committeeelectionvote_committee_election_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeelection',
            name='nomination_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committeeelection',
            name='nomination_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committeeelection',
            name='phase',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='committeeelection',
            name='voting_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committeeelection',
            name='voting_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
