# Generated by Django 4.0.6 on 2022-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_alter_committeeelection_nomination_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
