# Generated by Django 4.0.6 on 2022-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_nominee_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeelection',
            name='no_of_candidates',
            field=models.IntegerField(default=0),
        ),
    ]
