# Generated by Django 4.0.6 on 2022-08-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_owner_floor_no_remove_owner_unit_no_and_more'),
        ('election', '0014_committeemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.building')),
            ],
            options={
                'db_table': 'committee_position',
            },
        ),
    ]
