# Generated by Django 4.0.6 on 2022-08-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_remove_owner_floor_no_remove_owner_unit_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True)),
                ('date', models.DateTimeField(default=0, null=True)),
                ('transaction_no', models.CharField(max_length=30, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.building')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.owner')),
            ],
            options={
                'db_table': 'fund',
            },
        ),
    ]
