# Generated by Django 4.0.6 on 2022-08-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='amount',
            new_name='paid_amount',
        ),
    ]
