# Generated by Django 4.0.6 on 2022-08-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_amount_expense_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
