# Generated by Django 4.0.6 on 2022-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.TextField(),
        ),
    ]
