# Generated by Django 4.0.6 on 2022-08-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='comment',
        ),
    ]
