# Generated by Django 4.0.6 on 2022-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_expense_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
