# Generated by Django 4.0.6 on 2022-08-28 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0004_alter_usersubscription_subscription_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0007_expense_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_amount', models.FloatField(default=0, null=True)),
                ('due_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False, help_text='True: paid,False: unpaid')),
                ('transaction_number', models.CharField(blank=True, max_length=30, null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
