# Generated by Django 4.0.6 on 2022-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
