# Generated by Django 4.0.6 on 2022-08-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0004_alter_usersubscription_subscription_date'),
        ('finance', '0009_bill_description_bill_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='null means service charge', null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.serviceprovider'),
        ),
    ]
