# Generated by Django 4.0.6 on 2022-08-29 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0005_alter_usersubscription_subscription_date'),
        ('finance', '0010_alter_bill_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='package',
            field=models.ForeignKey(blank=True, help_text='null means service charge', null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.servicepackage'),
        ),
    ]
