# Generated by Django 4.0.6 on 2022-08-27 11:18

from django.db import migrations, models
import django.db.models.deletion
import serviceProvider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0005_rename_apartmentimages_apartmentimage'),
        ('user', '0009_remove_owner_floor_no_remove_owner_unit_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=serviceProvider.models.get_service_provider_image_upload_path)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bkash_acc_number', models.IntegerField(default=0)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.building')),
            ],
            options={
                'db_table': 'service provider',
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('fee', models.FloatField(default=0)),
                ('subscription_duration', models.FloatField(default=1, help_text='months')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.servicepackage')),
            ],
        ),
    ]
