# Generated by Django 4.0.6 on 2022-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
