# Generated by Django 4.0.6 on 2022-08-28 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceProvider', '0002_serviceprovider_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.servicepackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ApartmentSubscription',
        ),
    ]
