# Generated by Django 4.0.6 on 2022-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0005_alter_usersubscription_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='due',
            field=models.BooleanField(default=False),
        ),
    ]
