# Generated by Django 4.0.6 on 2022-07-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_building_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('bkash_acc_number', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.AlterModelTable(
            name='building',
            table='building',
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('departure_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('apartment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.owner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_user',
            },
        ),
    ]
