# Generated by Django 4.0.6 on 2022-07-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_owner_image_tenant_image_alter_tenant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.building'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.building'),
        ),
    ]
