# Generated by Django 4.0.6 on 2022-07-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_owner_building_tenant_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='building',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='building',
        ),
    ]
