# Generated by Django 4.0.6 on 2022-08-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_owner_floor_no_owner_unit_no_tenant_floor_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='floor_no',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='unit_no',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='floor_no',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='unit_no',
        ),
        migrations.AddField(
            model_name='tenant',
            name='bkash_acc_number',
            field=models.IntegerField(default=0),
        ),
    ]
