# Generated by Django 4.0.6 on 2022-08-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
