# Generated by Django 4.0.6 on 2022-08-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='selected_option',
            field=models.TextField(blank=True),
        ),
    ]
